import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Box } from '@mui/system'
import * as StyleVar from '../components/Style'
import { Button } from '@mui/material'
import Image from 'next/image'
import ResponsiveSideBar from '@/components/Sidebar'
import ResponsiveAppBar from '@/components/Navbar'
import { authApi } from '@/axios-client'
import {LoginPayLoad} from '../model/auth'
import axios from 'axios'
import axiosClient from '@/axios-client/axios-client'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const user:LoginPayLoad = {
    username:'admin',
    password:'123',
  }

  const handleLogin = async() => {
    try {
      await (await axiosClient.post('/api/login',user)).data
    } catch(err){
      console.log("error:",err)
    }
  }

  return (
    <Box sx={{
      display: 'flex',
      overflow: 'hidden'
    }}>
      <ResponsiveSideBar />
      <ResponsiveAppBar>
        <Box sx={{
          display: 'flex',
          alignItems: 'center',
          flexDirection: 'column',
          gap: '50px',
        }}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Box sx={{
            background: StyleVar.lightWhite,
          }}>
            <Button sx={{
              border: '1px solid #000'
            }}
            onClick={handleLogin}
            >Log in right here</Button>
          </Box>

          <Image src="/university.png" alt="" width={1200} height={600} />

        </Box>
      </ResponsiveAppBar>
    </Box>
  )
}
